### ISSUE TITLE
Folder bind

### ISSUE THREAD

**Issue by mehmeh1z** [Lolle2000la/Image-Sort#335]
Hi!
Can you add a bind to transfer images to each separate folder?
Example:
I press the number 1 on the keyboard and the picture moves to the folder where the bind was placed for this number, etc

**Comment by Lolle2000la** [comment]
Hi!
I thought about your proposal and how to realize it and I think it would make Image Sort a lot better. I will definitely try my hand at it! However I cannot tell you when that will be. Currently I'm very busy with studying so it might happen when my next break comes, or next week, I don't know yet.
