### ISSUE TITLE
Show animation of '.gif' files

### ISSUE THREAD

**Issue by brachna** [Lolle2000la/Image-Sort#419]
Windows release as of Aug 14, 2022.

Right now it shows only first frame, sorting is troublesome.

**Comment by Lolle2000la** [comment]
I got a build running with animated gifs. I'm going to test and refactor it some more and then include it in the next version.

**Comment by Lolle2000la** [comment]
I've added animated gif support in [v2.11.0](https://github.com/Lolle2000la/Image-Sort/releases/tag/v2.11.0). It is marked as prerelease for now as I have not done extensive testing. If nobody complains about issues, I will mark it as stable.

Please feel free to try it and test if it causes any issues. And thank you for the suggestion.

**Comment by brachna** [comment]
It's working, nice.
Maybe don't play animations in thumbnails though, when folder is filled with gifs it puts some strain on pc.

**Comment by Lolle2000la** [comment]
I've added an option in #421. Release [v2.11.1](https://github.com/Lolle2000la/Image-Sort/releases/tag/v2.11.1) now includes it.

It's also still set to prerelease, but I will mark it as stable once it's been out for a while without reports of serious bugs.

**Comment by Lolle2000la** [comment]
A version including animated gif support is now marked as stable, so I'm closing this issue.
