### ISSUE TITLE
A jpg image crashes the app (image included)

### ISSUE THREAD

**Issue by brachna** [Lolle2000la/Image-Sort#422]
Windows 10
Release [v2.11.1](https://github.com/Lolle2000la/Image-Sort/releases/tag/v2.11.1)

If folder contains attached jpg the app will crash.
![248](https://user-images.githubusercontent.com/5756107/194732523-c06d9050-c09a-4124-8c0b-682cb946ab2e.jpg)

**Comment by Lolle2000la** [comment]
It seems the image file has a bad format, which caused some exceptions to be thrown. This can sometimes happen with images, often they will still be shown normally by many programs. In this case, the same field of metadata seems to be set twice.

Those kind of issues were not catched by the error handling code, instead "sidestepping" it through the depths of WPF (what makes the UI) and the gif animation library I used, which has now been fixed. The image will now be displayed correctly in [v2.11.2](https://github.com/Lolle2000la/Image-Sort/releases/tag/v2.11.2).
