### ISSUE TITLE
Undo causes crash

### ISSUE THREAD

**Issue by sntrenter** [Lolle2000la/Image-Sort#444]
**Describe the bug**
Undo button causes Crash

**To Reproduce**
1. accidentally delete something
2. press undo
3. note crash

**Expected behavior**
Doesn't Crash

**Desktop (please complete the following information):**
 - OS: Win10
 - Architecture: x86
 - Version: [v2.11.4](https://github.com/Lolle2000la/Image-Sort/tree/v2.11.4)

**Comment by sntrenter** [comment]
it appears to work when clicked with the key binding, but pressing the button can cause a crash

**Comment by Lolle2000la** [comment]
Thank you for your report. Does this happen with all images? I cannot reproduce with the botton or the key binding on my machine.

**Comment by sntrenter** [comment]
It seems the issue resolved itself. I hadn't used the recycle bin in a while so maybe it had a problem initially undoing things?
I'll close for now and reopen if I experience the issue again and can narrow down what causes it.
