### ISSUE TITLE
Some images appear sideways

### ISSUE THREAD

**Issue by sntrenter** [Lolle2000la/Image-Sort#445]
**Describe the bug**

**To Reproduce**
1. Load in images that come from an Iphone

**Expected behavior**
they load in the correct way

**Screenshots**
![image](https://user-images.githubusercontent.com/22524502/212450281-233dfd75-431c-4c01-b283-18b529685d98.png)
![image](https://user-images.githubusercontent.com/22524502/212450304-082c53d4-3390-45c5-8fb2-0843c92b0b69.png)
![57712417352__5A4F55BB-7864-4F01-8772-9A53F9484D54](https://user-images.githubusercontent.com/22524502/212450311-463a1de1-fe48-469a-b15b-d5e9ade9540e.JPG)

**Desktop (please complete the following information):**
OS: Win10
Architecture: x86
Version: [v2.11.4](https://github.com/Lolle2000la/Image-Sort/tree/v2.11.4)

**Additional context**
This is a problem on some sites like 4chan with mobile images, not sure if related but all images I have had an issue with have been mobile

**Comment by Lolle2000la** [comment]
Thank you for your report. This bug should be fixed now. The newest stable update should already contain the fix.
