### ISSUE TITLE
Play animated WebP files

### ISSUE THREAD

**Issue by str-Luke** [Lolle2000la/Image-Sort#503]
Currently GIFs are supported nicely, however many modern applications and websites utilize WebP files for improved quality and storage.

WebP images can already be displayed, but animated WebP files only display the first frame. Hopefully this would be a simple addition as WebP images are already being displayed, and animated GIFs are already functional.

**Comment by Lolle2000la** [comment]
Thank you for the suggestion. Image Sort relies on WPF Imaging to render images. Originally it doesn't even support animated gifs. For that I've relied on [WPF Animated GIF](https://github.com/XamlAnimatedGif/WpfAnimatedGif). It seems a similar solution for animated webp files does not exist yet, and developing it myself is a big task that is out of scope for this project.
