### ISSUE TITLE
Option/Toggle to Add/Remove Context Menu "Add to Image Sort" on Folder or Drive

### ISSUE THREAD

**Issue by mauserk98grenaderifle** [Lolle2000la/Image-Sort#584]
It is helpful to add an option to Add/Remove Context Menu "Add to Image Sort" on Folder/Recycle Bin or Drive. I dont want to clutter my right click menu.

**Comment by Lolle2000la** [comment]
Hi! Thank you for the suggestion! That definitely sounds like something I want to add. Currently, I am busy writing my graduation thesis so I cannot work on this but in the meantime, if someone wants to pick this up, they are welcome to open a pull request.

**Comment by Lolle2000la** [comment]
Next version will contain the option to remove the entry in the context menu.

**Comment by Lolle2000la** [comment]
I have just published [v2.13.0](https://github.com/Lolle2000la/Image-Sort/releases/tag/v2.13.0), which contains the option. Thank you for waiting all this time, I'm sorry that it took this long.

**Comment by mauserk98grenaderifle** [comment]
Thank you, your effort is appreciated.
